### ISSUE TITLE
Swiftgen Assets in wrong order

### ISSUE THREAD

**Issue by eaigner** [SwiftGen/SwiftGen#382]
We have a swiftgen distribution and an assets file checked into our repo. Now when I check this out, swiftgen always regenerates my assets in the wrong order, despite no changes were made. The checked in `Assets.swift` has its members alphabetically sorted - the newly generated one does not.

Why?

We generate assets like this where `${TOOLS}` is the tools folder in our repo

    "${TOOLS}/SwiftGen/bin/swiftgen" images -t swift3 --output Project/Assets.swift Project/

**Comment by djbe** [comment]
Pretty sure you have an older SwiftGen version with this bug:
https://github.com/SwiftGen/SwiftGen/issues/336
https://github.com/SwiftGen/SwiftGenKit/issues/56

It should have been fixed in 5.2.0, could check if you're using the latest SwiftGen version (5.2.1)?

**Comment by djbe** [comment]
Closing due to inactivity. OP was probably using an outdated version of SwiftGen. If this is not the case, please reopen the issue.

**Comment by yonaskolb** [comment]
I'm seeing this as well.
It seems the sorting is taking the casing of the files in the asset catalog into account. So sometimes `ZIcon` is sorted before `aIcon`, but behaviour is different on different machines. The incorrect sorting is occurring on High Sierra with APFS

**Comment by AliSoftware** [comment]
Incorrect sorting of files in High Sierra + APFS is expected as reported in https://github.com/SwiftGen/SwiftGenKit/issues/56 because High Sierra doesn't guarantee anymore the order of the array returned by `contentsOfDirectory(atPath:)`. So not surprising that this behaviour is random and only on High Sierra + APFS.

@yonaskolb Are you sure you're using a recent version of SwiftGen? Which one are you using?
Any version of SwiftGen which links to SwiftGenKit + PathKit that include the bug fix for this shouldn't have the issue anymore…

**Comment by eaigner** [comment]
It still sorts wrong, despite @djbe claiming it being fixed. I still get a completely random order (macOS on APFS).

**Comment by djbe** [comment]
@yonaskolb @eaigner Could you check if this is still the case with SwiftGen 6.0?

**Comment by yonaskolb** [comment]
Oh sorry, forgot to give an update on this. I don't have access to those machines anymore, but we ended up discovering it was casing issue and related to git.

So some machines had `ZIcon` checkout out and some had `zIcon` checked out. It was renamed on one persons machine but that doesn't cause a diff so nothing was committed.
The other issue was that SwiftGen was taking casing into account when sorting so `ZIcon` came before `aIcon`. We just rechecked out those files from scratch and it was all good.
SwiftGen should maybe use a localized sort instead of a plain string sort. That would fix the casing issue.
eg:
```diff
- .sorted { $0 < $1 }
+ .sorted { $0.localizedStandardCompare($1) == .orderedAscending }
```

**Comment by enhorn** [comment]
I'm getting re-shuffled assets as well.
```
swiftgen --version
SwiftGen v6.1.0 (Stencil v0.13.1, StencilSwiftKit v2.7.2, SwiftGenKit v6.1.0)
```
